### Cameras ###
# For onboard camera give permissions to hass
# sudo usermod -a -G video hass
- platform: rpi_camera
  name: Server Room Camera
  image_width: 640
  image_height: 480
  image_quality: 7
  image_rotation: 180
  timelapse: 1000
  horizontal_flip: 0
  vertical_flip: 0
  file_path: /home/hass/picamera/image.jpg
