homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  temperature_unit: F
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  unit_system: imperial
  elevation: 23

http:
  api_password: !secret http_password

nest:
  username: !secret nest_username
  password: !secret nest_password

ifttt:
  key: !secret ifttt_api_key

climate:
  platform: nest

# Enables Zwave Aeotec Z-Stick Gen 5
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

mqtt:
  broker: !secret localhost
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password


#GPIO sensor
#give correct permissions with "sudo adduser hass gpio"
binary_sensor:
  platform: rpi_gpio
  ports:
    17: server_room_motion_sensor
  pull_mode: "UP"
  bouncetime: 50
  invert_logic: false

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################

sensor: !include sensors.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
automation: !include automation.yaml
device_tracker: !include device_tracker.yaml
switch: !include switches.yaml
notify: !include notify.yaml
group: !include groups.yaml
light: !include lights.yaml

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

logbook:
logger:
frontend:
history:
discovery:
sun:
conversation:
updater:
