homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  temperature_unit: F
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  unit_system: imperial
  elevation: 23
# View all events in a logbook
logbook:

# Enables the frontend
frontend:

http:
  api_password: !secret http_password

# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:

nest:
  username: !secret nest_username
  password: !secret nest_password

climate:
  platform: nest

# Enables Zwave Aeotec Z-Stick Gen 5
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

# Enables Lifx Light Bulbs
light:
  platform: lifx
  allow_unreachable: true

automation: !include automation.yaml

device_tracker: !include device_tracker.yaml

switch: !include switches.yaml

notify: !include notify.yaml

group: !include groups.yaml

mqtt:
  broker: !secret localhost
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password

sensor: !include sensors.yaml

zone: !include zones.yaml

camera: !include cameras.yaml

#GPIO sensor
#give correct permissions with "sudo adduser hass gpio"
binary_sensor:
  platform: rpi_gpio
  ports:
    17: server_room_motion_sensor
  pull_mode: "UP"
  bouncetime: 50
  invert_logic: false
