- platform: wake_on_lan
  mac_address: !secret mac_my_computer
  name: "My Computer"
  host: !secret my_computer_ip

#testing
- platform: wake_on_lan
  mac_address: !secret mac_amazon_dash_button
  name: "Amazon Button"
  host: !secret amazon_dash_ip
