- platform: wake_on_lan
  mac_address: !secret mac_my_computer
  name: "My Computer"
  host: "10.0.0.80"

#testing
- platform: wake_on_lan
  mac_address: !secret mac_amazon_dash_button
  name: "Amazon Button"
  host: "10.0.0.94"
